<?php
/**
 * Created by PhpStorm.
 * User: Adminstrator
 * Date: 2018/7/31
 * Time: 23:33
 * Comment: 基础验证器
 */
namespace app\admin\validate;

use think\Validate;

class BasisValidate extends Validate {

    /**
     * @param array $data
     * @param array $rules
     * @param string $scene
     * @return bool
     */
    public function check($data, $rules = [], $scene = '')
    {
        return parent::check($data, $rules, $scene); // TODO: Change the autogenerated stub
    }
}