<?php
/**
 * Created by PhpStorm.
 * User: Adminstrator
 * Date: 2018/7/31
 * Time: 23:12
 * Comment: 后台基础控制器
 */
namespace app\admin\controller;

use think\Controller;

class BasisController extends Controller {

    /**
     * 初始化函数
     */
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

}