<?php
/**
 * Created by PhpStorm.
 * User: Adminstrator
 * Date: 2018/7/22
 * Time: 17:47
 * Comment: 基礎控制器
 */
namespace app\index\controller;

use think\Controller;

class BaseController extends Controller {

    /**
     * 初始化函数
     */
    protected function _initialize() {
        header('Content-Type:text/html;charset=utf-8');

        //获得首页导航数据
        $category = model('category')
            ->where(array('is_recommend' => 1))
            ->order('list_order desc')
            ->limit(6)
            ->select();

        $navigation = array();
        //遍历分类
        foreach ($category as $key => $vo) {
            $navigation[$key]['cate_id'] = $vo['id'];               //分类主键
            $navigation[$key]['cate_name'] = $vo['name'];           //分类名称
            $navigation[$key]['pic_path'] = $vo['pic_path'];        //分类图片
            $navigation[$key]['common'] = model('Common')
                ->where(array('cate_id' => $vo['id']))
                ->select();                                         //Common数据
            $navigation[$key]['news'] = model('news_config')
                ->where(array('cate_id' => $vo['id']))
                ->select();                                         //新闻数据
        }

        //分配数据到前端
        $this->assign('navigation', $navigation);

        //新闻中心
        $newsList = model('news_class')
            ->where('rid = 2 and status = 1')
            ->order('list_order,id')
            ->select();

        //分配数据到前端
        $this->assign('newsList', $newsList);

        //二维码
        $codeList = model('atm')
            ->where('class_id = 5 and status =1')
            ->order('list_order desc, id')
            ->limit(3)
            ->select();

        foreach ($codeList as $key => $item) {

        }

        //分配数据到前端
        $this->assign('codeList', $codeList);

        /* */
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

}